name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libncurses-dev libncursesw5-dev curl unzip tar
    - name: Install vcpkg
      run: cargo install cargo-vcpkg
    - name: Build vcpkg
      run: cargo vcpkg build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
